### ISSUE TITLE
UA別プリセットの検討

### ISSUE THREAD

**Issue by onihusube** [onihusube/2chAPIProxy#8]
# 基本構想

`preset.yaml`のようなファイルを導入して、ここにUA別にプリセットを書いておいて読み込ませて使用するようにするとする。

```yaml
- style
  - UA : Monazilla/1.00 JaneStyle/4.23 Windows/10.0.19044
  - Appkey : ****
  - HMkey : ****
  - PostFiledOrder : submit&FROM&mail&MESSAGE&bbs&key&time
  - ThreadPostFieldOrder : submit&FROM&mail&MESSAGE&bbs&key&time
  - NonceType : Sec
  - RefererType : Board
  - KeepAlive : false
- mate
  - ...
```

みたいな構文を想定。

`BoardSettings.yaml`の各設定には新しい`Preset`のようなプロパティを追加して、これによって板毎に参照するUA設定を制御する。

- メリット
  - 板毎設定とUA/キー関連設定を分離できる
  - プロファイル的な使い方に拡張可能
- デメリット
  - 設定ファイルが増える
  - 書き込み関連設定のほとんどがUIから制御できなくなる
    - UIの設定は読み込みに関するもの、という分離にはなる・・・？
  - UIと設定項目の重複がある
  - 設定変更に再起動が必要 

# 検討項目

- [x] 使用するプリセットの選択について（いくつか実装が考えられる
  1. ~~書き込みUAとプリセット名のマッチングをとって、使用するプリセットを自動選択する~~
  2. 書き込みUAは無視して`BoardSettings.yaml`で使用するプリセットを指定する
    - UIから指定できるようにするとして、板毎設定の共通設定との関係をどうするか？
  4. ~~1と2を両立する~~
      - 共通設定の扱いはどうするか？ 
- [x] プリセットに必要なプロパティ
- [x] YamlDotNetは列挙値をデシリアライズできるのか？
    - 普通にできた 
- [x] 各プリセット毎のmonakeyをどこに保存するか？
  - yamlは読み込み専用にしたい気持ちがある
  - `settings.xml`に1つの文字列にして保存
- [x] 板別設定の共通設定の扱い
   - 全て無視されるようになるため、必要なくなる
   - プリセットが存在しない時のフォールバック先にする？
- [ ] UI上の設定との優先度付けなど
   - 書き込みUAの扱いをどうするか
      - プリセットが無い場合と旧書き込み方式でのみ使用される
- [ ] 実装時の優先順位
   - 指定されたプリセットを常に使用する
   - 板別設定はプリセット指定とUAのみを上書きする
   - プリセットが無い場合に、旧（現在の）書き込み設定を使用
   - 旧書き込み方式では旧（現在の）の設定を使用
- [ ] 現在の設定項目の後方互換性について
  - 少なくともエラーにならないようにする必要がある
  - プリセットが無い場合にのみ既存設定を使用する
# 関連

#2 #6 

ご意見等ありましたらご自由にどうぞ
